//* SAMPLE INFO */
INSERT INTO _catalogs (catType,itemName) VALUES ('accidentTypes','001-Collision')
INSERT INTO _catalogs (catType,itemName) VALUES ('accidentTypes','002-Robbery')
INSERT INTO _catalogs (catType,itemName) VALUES ('billingTypes','Insurance')
INSERT INTO _catalogs (catType,itemName) VALUES ('billingTypes','Lodging')
INSERT INTO _catalogs (catType,itemName) VALUES ('boatTypes','Sea-Ray')
INSERT INTO _catalogs (catType,itemName) VALUES ('boatTypes','Slickcraft')
INSERT INTO _catalogs (catType,itemName) VALUES ('claimTypes','ACVS')
INSERT INTO _catalogs (catType,itemName) VALUES ('claimTypes','ADJ')
INSERT INTO _catalogs (catType,itemName) VALUES ('lossTypes','Accident Reconstruction')
INSERT INTO _catalogs (catType,itemName) VALUES ('lossTypes','Adjustment')
INSERT INTO _catalogs (catType,itemName) VALUES ('paymentTypes','Bank Card')
INSERT INTO _catalogs (catType,itemName) VALUES ('paymentTypes','Cash')
INSERT INTO _catalogs (catType,itemName) VALUES ('referenceTypes','Potential Agent')
INSERT INTO _catalogs (catType,itemName) VALUES ('referenceTypes','Labs')
INSERT INTO _catalogs (catType,itemName) VALUES ('salvageTypes','Salvage Boat')
INSERT INTO _catalogs (catType,itemName) VALUES ('salvageTypes','Salvage Chemical')
INSERT INTO _catalogs (catType,itemName) VALUES ('sourceTypes','AAA Marine')
INSERT INTO _catalogs (catType,itemName) VALUES ('sourceTypes','1st Midwest Bank')
INSERT INTO _catalogs (catType,itemName) VALUES ('fireClaimTypes','SFAZ01-State Farm Ins/FCC/AZ')
INSERT INTO _catalogs (catType,itemName) VALUES ('fireClaimTypes','SFB001-State Farm Ins/FCC/IL')